# Generated by Django 2.0.7 on 2018-12-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CinModel',
        ),
        migrations.RemoveField(
            model_name='mcainformation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mcainformation',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='mcainformation',
            name='date_lastupdated',
        ),
        migrations.RemoveField(
            model_name='mcainformation',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='mcainformation',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='mcainformation',
            name='file_upload_date',
        ),
        migrations.AddField(
            model_name='mcainformation',
            name='today',
            field=models.BooleanField(default=False),
        ),
    ]
