# Generated by Django 2.0.7 on 2018-12-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roc', '0002_auto_20181227_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcainformation',
            old_name='today',
            new_name='doc_present',
        ),
    ]
