# Generated by Django 2.0.7 on 2018-12-27 07:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CinModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_cin', models.CharField(max_length=255)),
                ('today', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='McaInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_cin', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_upload_date', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_lastupdated', models.DateField(auto_now=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('timestamp_lastupdated', models.DateTimeField(auto_now=True)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
