# Generated by Django 2.0.9 on 2018-12-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roc', '0003_auto_20181227_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcainformation',
            name='doc_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
