# Generated by Django 2.1.4 on 2019-04-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roc', '0004_mcainformation_doc_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcainformation',
            name='other_eform_documents_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcainformation',
            name='other_eform_documents_present',
            field=models.BooleanField(default=False),
        ),
    ]
